name: JDK cache benchmark dispatcher

on:
  workflow_dispatch:
    inputs:
      cleanup-caches:
        description: Delete benchmark caches after measuring them
        required: true
        type: boolean
        default: true

permissions:
  actions: write
  contents: read

jobs:
  benchmark:
    uses: actions/setup-java-benchmarks/.github/workflows/jdk-cache.yml@brunoborges-benchmark-jdk-cache
    with:
      cleanup-caches: ${{ inputs.cleanup-caches }}
